package:
  name: rise
  version: "5.0.0"

source:
  path: ../

build:
  string: "py{{ environ.get('PY_VER').replace('.', '') }}\
          {% if environ.get('RISE_RELEASE') == '1' %}\
            _{{ environ.get('RISE_BUILD_NUMBER', '0') }}\
          {% else %}\
            _{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}"

requirements:
  build:
    - python
    - notebook >=5.0.0
  run:
    - python
    - notebook >=5.0.0

test:
  requires:
    - python
    - notebook >=5.0.0

about:
  home: https://github.com/damianavila/RISE
  license: BSD 3-Clause
  license_file: LICENSE.md
